DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS dashboards;
DROP TABLE IF EXISTS sources;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_by INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT UNIQUE NOT NULL,
  route TEXT NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE dashboards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_by INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  source INTEGER NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users (id)
  FOREIGN KEY (source) REFERENCES sources (id)
);